version: "3.3"
services:
  backend:
    build: .
    volumes:
      - ./config/prod.env:/journal/config/prod.env
      - ./secrets.json:/secrets/secret.json
      - .:/journal/
    ports:
      - "8000:8000"
    deploy:
      replicas: 3
      restart_policy:
        condition: any
    networks:
      - journal
    environment:
      - DJANGO_MIGRATE=off
      - DJANGO_COLLECTSTATIC=off
      - IS_PROD=true
  db:
    image: postgres:latest
    volumes:
      - journal_db:/var/lib/postgresql/data/
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - journal

networks:
  journal:

volumes:
  journal_db:
