# Generated by Django 2.2.7 on 2020-06-17 11:02

from django.db import migrations, models


def create_singleton_me(apps, schema_editor):
    Me = apps.get_model('me', 'Me')
    me = Me()
    me.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=255)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='me')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('mobile', models.TextField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('gitlab', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_singleton_me)
    ]
