# Generated by Django 2.2.7 on 2020-06-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='me',
            options={'verbose_name': ('Me',), 'verbose_name_plural': 'Me'},
        ),
        migrations.AlterField(
            model_name='me',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
