# Generated by Django 3.0.7 on 2020-06-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='work')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('order', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='work')),
            ],
        ),
        migrations.CreateModel(
            name='Techonology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('work', models.ManyToManyField(blank=True, null=True, related_name='techs', to='works.Work')),
            ],
        ),
    ]
