# Generated by Django 3.0.7 on 2020-06-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Techonology',
            new_name='Technology',
        ),
        migrations.AlterField(
            model_name='work',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
