# Generated by Django 3.0.7 on 2020-06-19 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_auto_20200619_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['order']},
        ),
    ]
