# Generated by Django 3.0.7 on 2020-06-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_auto_20200619_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
