# Generated by Django 3.0.7 on 2020-06-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_auto_20200619_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to='work'),
        ),
    ]
