# Generated by Django 2.1.3 on 2018-11-03 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='pagecategory',
            options={'verbose_name_plural': 'Page Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notebook.Page'),
            preserve_default=False,
        ),
    ]
