# Generated by Django 2.1.3 on 2018-11-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='journal')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='banner',
            field=models.ImageField(blank=True, upload_to='journal'),
        ),
    ]
