# Generated by Django 2.1.3 on 2018-11-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_auto_20181103_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='page',
        ),
        migrations.AddField(
            model_name='category',
            name='page',
            field=models.ManyToManyField(to='notebook.Page'),
        ),
    ]
